site_name: vivy
site_url: https://sqrtrae.github.io/vivy
repo_url: https://github.com/sqrtrae/vivy
repo_name: sqrtrae/vivy

nav:
  - Getting Started:
      - Installation: index.md
      - Basic Usage: usage.md
      - Making Your Own Builders: extend.md
  - API Reference: api/index.md
  - Changelog: changelog.md

theme:
  name: material
  locale: en
  palette:
    scheme: default
    primary: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

extra_css:
  - css/material.css

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
