site_name: vivy
site_url: https://sqrtrae.github.io/vivy
repo_url: https://github.com/sqrtrae/vivy
repo_name: sqrtrae/vivy

nav:
  - Getting Started:
      - Installation: guide/install.md
      - Basic Usage: guide/usage.md
      - Included Builders:
          - Scalar: guide/builders/scalar.md
          - List: guide/builders/list.md
          - Set: guide/builders/set.md
      - Making Your Own Builders: guide/extend.md
  - API Reference: api/index.md
  - Changelog: changelog.md

theme:
  name: material
  locale: en
  palette:
    scheme: default
    primary: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

extra_css:
  - css/material.css

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
